# -*- coding: utf-8 -*-
"""ART Adversarial attack (FGSM).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cETFsDRFduw2UusfPMQ2h9L-hg6cf2LE
"""

# Step 1: Install dependencies
!pip install -q tensorflow tensorflow-datasets adversarial-robustness-toolbox

# Step 2: Import libraries
import tensorflow as tf
import tensorflow_datasets as tfds
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from art.estimators.classification import TensorFlowV2Classifier
from art.attacks.evasion import FastGradientMethod
from art.utils import to_categorical

# Step 3: Parameters
IMG_SIZE = 160
BATCH_SIZE = 32
EPOCHS = 15
NUM_CLASSES = 2

# Step 4: Load 1000 cats + 1000 dogs
(train_raw, test_raw), _ = tfds.load('cats_vs_dogs', split=['train[:80%]', 'train[80%:]'],
                                     with_info=True, as_supervised=True)

cat_imgs, dog_imgs = [], []
for img, label in tfds.as_numpy(train_raw):
    if label == 0 and len(cat_imgs) < 500:
        cat_imgs.append((img, label))
    elif label == 1 and len(dog_imgs) < 500:
        dog_imgs.append((img, label))
    if len(cat_imgs) == 500 and len(dog_imgs) == 500:
        break

data = cat_imgs + dog_imgs
np.random.shuffle(data)

x_data, y_data = [], []
for img, label in data:
    img = tf.image.resize(img, (IMG_SIZE, IMG_SIZE))
    img = tf.cast(img, tf.float32) / 255.0
    x_data.append(img.numpy())
    y_data.append(label)

x_data = np.array(x_data)
y_data = np.array(y_data)
y_data_cat = to_categorical(y_data, NUM_CLASSES)

# Step 5: Define model using pretrained MobileNetV2
def create_model(fine_tune=False):
    base_model = tf.keras.applications.MobileNetV2(input_shape=(IMG_SIZE, IMG_SIZE, 3),
                                                   include_top=False,
                                                   weights='imagenet')
    base_model.trainable = fine_tune  # fine-tuning toggle

    x = tf.keras.layers.GlobalAveragePooling2D()(base_model.output)
    x = tf.keras.layers.Dropout(0.3)(x)
    x = tf.keras.layers.Dense(128, activation='relu')(x)
    outputs = tf.keras.layers.Dense(NUM_CLASSES, activation='softmax')(x)
    return tf.keras.Model(inputs=base_model.input, outputs=outputs)

# Step 6: Image Augmentation + Validation Split
datagen = ImageDataGenerator(
    validation_split=0.2,
    rotation_range=15,
    width_shift_range=0.1,
    height_shift_range=0.1,
    zoom_range=0.1,
    horizontal_flip=True
)
datagen.fit(x_data)

train_gen = datagen.flow(x_data, y_data_cat, batch_size=BATCH_SIZE, subset='training')
val_gen = datagen.flow(x_data, y_data_cat, batch_size=BATCH_SIZE, subset='validation')

# Step 7: Train clean model with early stopping
clean_model = create_model(fine_tune=False)
clean_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

early_stop = tf.keras.callbacks.EarlyStopping(patience=3, restore_best_weights=True)

clean_model.fit(train_gen,
                validation_data=val_gen,
                epochs=EPOCHS,
                callbacks=[early_stop],
                verbose=1)

# Optional fine-tuning (unfreeze base model)
clean_model.layers[0].trainable = True
clean_model.compile(optimizer=tf.keras.optimizers.Adam(1e-5),  # lower LR for fine-tuning
                    loss='categorical_crossentropy',
                    metrics=['accuracy'])

clean_model.fit(train_gen,
                validation_data=val_gen,
                epochs=5,
                verbose=1)

# Step 8: Poisoning setup with ART (FGSM)
poison_model = create_model(fine_tune=False)
poison_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

classifier = TensorFlowV2Classifier(
    model=poison_model,
    nb_classes=NUM_CLASSES,
    input_shape=(IMG_SIZE, IMG_SIZE, 3),
    loss_object=tf.keras.losses.CategoricalCrossentropy(),
    optimizer=tf.keras.optimizers.Adam(),
    clip_values=(0.0, 1.0)
)

fgsm = FastGradientMethod(estimator=classifier, eps=0.01)
x_poisoned = fgsm.generate(x=x_data)

# Step 9: Train poisoned model
classifier.fit(x_poisoned, y_data_cat, batch_size=BATCH_SIZE, nb_epochs=EPOCHS)

# Step 10: Prepare clean test set
x_test, y_test = [], []
for img, label in tfds.as_numpy(test_raw.take(200)):
    img = tf.image.resize(img, (IMG_SIZE, IMG_SIZE))
    img = tf.cast(img, tf.float32) / 255.0
    x_test.append(img.numpy())
    y_test.append(label)

x_test = np.array(x_test)
y_test_cat = to_categorical(np.array(y_test), NUM_CLASSES)

# Step 11: Evaluate both models
clean_acc = clean_model.evaluate(x_test, y_test_cat, verbose=0)[1]
predictions = classifier.predict(x_test)
poison_acc = np.mean(np.argmax(predictions, axis=1) == np.argmax(y_test_cat, axis=1))

print(f"✅ Clean-trained model accuracy on clean test set: {clean_acc:.4f}")
print(f"🚨 Poison-trained model accuracy on clean test set: {poison_acc:.4f}")

# Step 12: Visualize accuracy comparison
plt.bar(['Clean Model', 'Poisoned Model'], [clean_acc, poison_acc], color=['green', 'red'])
plt.ylabel('Accuracy')
plt.title('Clean vs Poisoned Model Accuracy on Clean Test Set')
plt.ylim([0, 1])
plt.show()

# Step 8.5: Visualize clean vs poisoned images
num_samples = 5  # Show 5 sample comparisons
plt.figure(figsize=(10, 4 * num_samples))

for i in range(num_samples):
    # Original
    plt.subplot(num_samples, 2, 2*i + 1)
    plt.imshow(x_data[i])
    plt.title("Original")
    plt.axis('off')

    # Poisoned
    plt.subplot(num_samples, 2, 2*i + 2)
    plt.imshow(x_poisoned[i])
    plt.title("FGSM")
    plt.axis('off')

plt.tight_layout()
plt.show()

import numpy as np

def calculate_average_snr(clean_images, poisoned_images):
    """Calculates the average Signal-to-Noise Ratio (SNR) between clean and poisoned images.

    Args:
        clean_images: A NumPy array of clean images.
        poisoned_images: A NumPy array of poisoned images.

    Returns:
        The average SNR across all image pairs.
    """

    if clean_images.shape != poisoned_images.shape:
        raise ValueError("Clean and poisoned images must have the same shape.")

    num_images = clean_images.shape[0]
    snr_values = []

    for i in range(num_images):
        signal = clean_images[i]
        noise = poisoned_images[i] - clean_images[i]

        # Calculate the power of the signal and noise
        signal_power = np.sum(signal**2)
        noise_power = np.sum(noise**2)

        # Avoid division by zero
        if noise_power == 0:
            snr = np.inf  # or a very large value
        else:
            snr = 10 * np.log10(signal_power / noise_power)  #SNR in dB

        snr_values.append(snr)

    return np.mean(snr_values)


# Example usage (assuming you have x_data and x_poisoned from your code)
average_snr = calculate_average_snr(x_data, x_poisoned)
print(f"Average SNR: {average_snr:.2f} dB")