# -*- coding: utf-8 -*-
"""research-inspired TUEs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c9k1X3bBNcSO73Fofd93gVIkIJqh2PC7
"""

# ============================================================
# TUEs – WINDOW-BASED (STRONGER FTV, NO OOM, NO BLACK) ✅ NEW
# Google Colab – COPY & RUN
# - window-based ลด OOM
# - save คงขนาดเดิม (ไม่ resize ตอน save)
# - NEW LOSS: maximize Feature Temporal Variance (FTV) จริงๆ
# - มี metric: Pixel TV + Feature TV (Pre-encode / Post-encode)
# ============================================================

!pip install -q opencv-python torch torchvision numpy tqdm ffmpeg-python

import os, cv2, torch
import numpy as np
import torch.nn.functional as F
from torchvision.models.video import r3d_18, R3D_18_Weights
from tqdm import tqdm
from google.colab import files
import time

# ---------------- Device ----------------
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

# ---------------- Download video ----------------
# !wget -q -O sample.mp4 https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4

# Changed video URL to a known good one from a public domain video archive
video_url = "https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4"
video_filename = "sample.mp4"

# Try to download the video, remove -q to see output for debugging
print(f"Attempting to download {video_filename} from {video_url}")
!wget -O {video_filename} {video_url}

# Check if the download was successful
if not os.path.exists(video_filename) or os.path.getsize(video_filename) == 0:
    print("\nWarning: Video file did not download correctly or is empty.")
    print("Please check the URL or your internet connection.")
    print("As an alternative, you can try to upload the video manually:")
    try:
        uploaded = files.upload()
        if video_filename in uploaded:
            print(f"Successfully uploaded {video_filename}")
        else:
            print("Manual upload failed or file not found in uploaded list.")
    except Exception as e:
        print(f"Error during manual upload: {e}")

# ---------------- Utils: load frames ----------------
def load_frames(video_path, max_frames=192):
    cap = cv2.VideoCapture(video_path)
    fps = cap.get(cv2.CAP_PROP_FPS)
    if fps is None or fps == 0:
        fps = 30.0

    frames = []
    while len(frames) < max_frames:
        ret, frame = cap.read()
        if not ret:
            break
        frames.append(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
    cap.release()

    print("Loaded frames:", len(frames), "FPS:", fps)
    return frames, fps

# ---------------- Resize (spatial only) for model ----------------
def resize_for_model(video, size=112):
    # video: (N,C,T,H,W)
    n, c, t, h, w = video.shape
    video2 = video.permute(0,2,1,3,4).reshape(n*t, c, h, w)
    video2 = F.interpolate(video2, size=(size, size), mode="bilinear", align_corners=False)
    video2 = video2.reshape(n, t, c, size, size).permute(0,2,1,3,4)
    return video2

# ---------------- Temporal variance (pixel) ----------------
def temporal_variance_cthw(video_cthw):
    # video_cthw: (C,T,H,W) in [0,1]
    diffs = video_cthw[:, 1:] - video_cthw[:, :-1]
    return diffs.pow(2).mean().item()

# ---------------- Flicker term on OUTPUT (stronger than delta-only) ----------------
def output_temporal_inconsistency(poisoned):
    # poisoned: (N,C,T,H,W)
    diffs = poisoned[:, :, 1:] - poisoned[:, :, :-1]
    return torch.mean(diffs**2)

# ---------------- Model (FP32 stable) ----------------
model = r3d_18(weights=R3D_18_Weights.DEFAULT).to(device).eval()
feature_model = torch.nn.Sequential(*list(model.children())[:-1]).to(device).eval()

# ============================================================
# Feature Temporal Variance (FTV) loss inside a window
# - take multiple sub-clips across time
# - maximize feature changes across time
# ============================================================
def ftv_loss_from_window(poisoned_small, clip_len=8, stride=4):
    """
    poisoned_small: (1,3,T,112,112)
    Return: scalar loss that is HIGH when feature changes across time are high
    """
    T = poisoned_small.shape[2]
    feats = []
    for t in range(0, T - clip_len + 1, stride):
        sub = poisoned_small[:, :, t:t+clip_len]            # (1,3,clip_len,112,112)
        feat = feature_model(sub).flatten(1)                # (1,dim)
        feats.append(feat)

    if len(feats) < 2:
        return torch.tensor(0.0, device=poisoned_small.device)

    feats = torch.cat(feats, dim=0)                         # (K,dim)
    diffs = feats[1:] - feats[:-1]
    return torch.mean(diffs**2)                             # high = more temporal disruption

# ============================================================
# TUEs poisoning for ONE WINDOW ✅ STRONGER LOSS
# - maximize FTV (feature temporal disruption)
# - add pixel flicker on output
# - keep perturbation bounded
# ============================================================
def poison_window(frames,
                 steps=30,
                 eps=20/255,
                 lr=2e-3,
                 w_ftv=1.5,
                 w_pix=0.3,
                 clip_len=8,
                 clip_stride=4):
    """
    frames: list RGB uint8 length T
    returns: poisoned_chunk_uint8, metrics dict (pre-encode)
    """
    video = np.stack(frames).astype(np.float32) / 255.0                 # (T,H,W,3)
    video = torch.from_numpy(video).permute(3,0,1,2).unsqueeze(0).to(device)  # (1,3,T,H,W)

    delta = torch.zeros_like(video, requires_grad=True)
    opt = torch.optim.Adam([delta], lr=lr)

    for _ in range(steps):
        opt.zero_grad()

        poisoned = torch.clamp(video + delta, 0, 1)

        # model view (112) only for feature loss
        poisoned_small = resize_for_model(poisoned)

        # NEW: maximize feature temporal variance (FTV)
        ftv = ftv_loss_from_window(poisoned_small, clip_len=clip_len, stride=clip_stride)

        # also encourage visible flicker in pixel domain (but keep small weight)
        pix_flicker = output_temporal_inconsistency(poisoned)

        # minimize negative => maximize both
        loss = -(w_ftv * ftv + w_pix * pix_flicker)

        loss.backward()
        opt.step()

        with torch.no_grad():
            delta.clamp_(-eps, eps)

    with torch.no_grad():
        out = torch.clamp(video + delta, 0, 1)

    # ---- metrics BEFORE encode ----
    clean_tv = temporal_variance_cthw(video.squeeze(0).detach().cpu())
    pois_tv  = temporal_variance_cthw(out.squeeze(0).detach().cpu())
    ratio_tv = (pois_tv / clean_tv) if clean_tv > 0 else float("inf")

    diff = (out - video).detach()
    l_inf = diff.abs().max().item()
    l2 = (torch.norm(diff).item() / diff.numel())

    # convert to uint8 frames (keep original H,W)
    out_np = out.squeeze(0).permute(1,2,3,0).cpu().numpy()
    out_np = np.clip(out_np, 0, 1)
    out_u8 = (out_np * 255).astype(np.uint8)

    metrics = {
        "pixel_tv_clean": clean_tv,
        "pixel_tv_pois": pois_tv,
        "pixel_tv_ratio": ratio_tv,
        "l_inf": l_inf,
        "l2_norm_per_elem": l2
    }
    return out_u8, metrics

# ============================================================
# SAFE Feature Temporal Variance metric (no RAM crash)
# ============================================================
@torch.no_grad()
def load_video_tensor(path, max_frames=128):
    cap = cv2.VideoCapture(path)
    frames = []
    while len(frames) < max_frames:
        ret, frame = cap.read()
        if not ret:
            break
        frames.append(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
    cap.release()
    video = np.stack(frames).astype(np.float32) / 255.0
    return torch.from_numpy(video).permute(3,0,1,2)  # (C,T,H,W)

@torch.no_grad()
def feature_temporal_variance_stream(video_cthw, clip_len=8, stride=2):
    C, T, H, W = video_cthw.shape
    prev_feat = None
    sum_sq = 0.0
    count = 0

    for t in range(0, T - clip_len + 1, stride):
        clip = video_cthw[:, t:t+clip_len].unsqueeze(0).to(device)  # (1,C,T,H,W)
        clip_small = resize_for_model(clip)
        feat = feature_model(clip_small).flatten(1).cpu()

        if prev_feat is not None:
            diff = feat - prev_feat
            sum_sq += diff.pow(2).mean().item()
            count += 1

        prev_feat = feat

        del clip, clip_small, feat
        if device == "cuda":
            torch.cuda.empty_cache()

    return sum_sq / max(count, 1)

# ---------------- Run (WINDOWED) ----------------
frames, fps = load_frames("sample.mp4", max_frames=192)

# reset output folder
if os.path.exists("frames"):
    for f in os.listdir("frames"):
        os.remove(os.path.join("frames", f))
else:
    os.makedirs("frames", exist_ok=True)

window = 24   # ~1 sec per window
idx = 0

# collect pre-encode metrics per window
pre_metrics = []

poison_start_time = time.time()

for i in tqdm(range(0, len(frames), window)):
    chunk = frames[i:i+window]
    if len(chunk) < 2:
        break

    poisoned_chunk_u8, m = poison_window(
        chunk,
        steps=30,        # ↑
        eps=20/255,       # ↑ stronger than 2/255
        lr=2e-3,         # ↑
        w_ftv=1.5,       # ↑ feature temporal disruption weight
        w_pix=0.3,       # small pixel flicker weight
        clip_len=8,
        clip_stride=4
    )
    pre_metrics.append(m)

    for f in poisoned_chunk_u8:
        cv2.imwrite(f"frames/{idx:05d}.png", cv2.cvtColor(f, cv2.COLOR_RGB2BGR))
        idx += 1

    if device == "cuda":
        torch.cuda.empty_cache()

poison_end_time = time.time()
poison_total_time = poison_end_time - poison_start_time

# ---------------- Encode (preserve temporal noise more) ----------------
# NOTE: use tune=grain + lower crf to keep flicker detail
!ffmpeg -y -framerate {fps} \
  -i frames/%05d.png \
  -c:v libx264 -preset slow -crf 14 -tune grain \
  -pix_fmt yuv420p tue_8sec_stronger.mp4

# ---------------- Quick visual check (non-black) ----------------
import matplotlib.pyplot as plt

def read_frame_at(path, frame_idx=30):
    cap = cv2.VideoCapture(path)
    cap.set(cv2.CAP_PROP_POS_FRAMES, frame_idx)
    ret, frame = cap.read()
    cap.release()
    if not ret:
        raise ValueError(f"Cannot read frame {frame_idx} from {path}")
    return cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

f1 = read_frame_at("sample.mp4", 30)
f2 = read_frame_at("tue_8sec_stronger.mp4", 30)

plt.figure(figsize=(10,4))
plt.subplot(1,2,1); plt.title("Original"); plt.imshow(f1); plt.axis("off")
plt.subplot(1,2,2); plt.title("Poisoned (Stronger)"); plt.imshow(f2); plt.axis("off")
plt.show()

# ---------------- Aggregate PRE-ENCODE pixel metrics ----------------
avg_clean_tv = np.mean([m["pixel_tv_clean"] for m in pre_metrics])
avg_pois_tv  = np.mean([m["pixel_tv_pois"]  for m in pre_metrics])
avg_ratio_tv = np.mean([m["pixel_tv_ratio"] for m in pre_metrics])
avg_linf     = np.mean([m["l_inf"] for m in pre_metrics])

print("\n======== PRE-ENCODE (WINDOW AVG) ========")
print("Pixel Temporal Variance (Clean):", avg_clean_tv)
print("Pixel Temporal Variance (Poison):", avg_pois_tv)
print("Pixel Variance Ratio:", avg_ratio_tv)
print("L_inf (max perturbation):", avg_linf)

# ---------------- Post-encode Pixel TV ----------------
orig_t = load_video_tensor("sample.mp4", max_frames=192)
pois_t = load_video_tensor("tue_8sec_stronger.mp4", max_frames=192)

tv_orig_post = temporal_variance_cthw(orig_t)
tv_pois_post = temporal_variance_cthw(pois_t)

print("\n======== POST-ENCODE PIXEL METRICS (AFTER H.264) ========")
print("Pixel Temporal Variance (Clean):", tv_orig_post)
print("Pixel Temporal Variance (Poison):", tv_pois_post)
print("Pixel Variance Increase Ratio:", (tv_pois_post / tv_orig_post) if tv_orig_post > 0 else float("inf"))

# ---------------- Feature Temporal Variance (FTV) PRE/POST ----------------
# (วัดจากไฟล์ mp4 แบบ safe)
orig_ftv = feature_temporal_variance_stream(load_video_tensor("sample.mp4", 128), clip_len=8, stride=2)
pois_ftv = feature_temporal_variance_stream(load_video_tensor("tue_8sec_stronger.mp4", 128), clip_len=8, stride=2)

print("\n======== FEATURE TEMPORAL VARIANCE (SAFE) ========")
print("Feature Temporal Variance (Clean): ", orig_ftv)
print("Feature Temporal Variance (Poison):", pois_ftv)
print("FTV Ratio:", (pois_ftv / orig_ftv) if orig_ftv > 0 else float("inf"))

print(f"Total poisoning time (exclude load/encode): {poison_total_time:.2f} seconds")

files.download("tue_8sec_stronger.mp4")

# ============================================================
# VICTIM TEST: SlowFast FTV (COPY & RUN)
# ใช้ไฟล์ clean / poisoned ที่มีอยู่แล้ว
# ============================================================

!pip install -q pytorchvideo

import torch
import cv2
import numpy as np
import torch.nn.functional as F
from pytorchvideo.models.hub import slowfast_r50

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

# ---------------- Load video as tensor ----------------
@torch.no_grad()
def load_video_tensor(path, max_frames=128):
    cap = cv2.VideoCapture(path)
    frames = []
    while len(frames) < max_frames:
        ret, frame = cap.read()
        if not ret:
            break
        frames.append(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
    cap.release()

    video = np.stack(frames).astype(np.float32) / 255.0
    # (C,T,H,W)
    return torch.from_numpy(video).permute(3,0,1,2)

# ---------------- Resize for model ----------------
def resize_for_model(video, size=112):
    # video: (1,C,T,H,W)
    n,c,t,h,w = video.shape
    video2 = video.permute(0,2,1,3,4).reshape(n*t, c, h, w)
    video2 = F.interpolate(video2, size=(size,size), mode="bilinear", align_corners=False)
    video2 = video2.reshape(n, t, c, size, size).permute(0,2,1,3,4)
    return video2

# ---------------- SlowFast input helper ----------------
def make_slowfast_input(video_cthw, alpha=4):
    # video_cthw: (C,T,H,W)
    fast = video_cthw.unsqueeze(0)        # (1,C,T,H,W)
    slow = fast[:, :, ::alpha]            # temporal subsample
    return [slow.to(device), fast.to(device)]

# ---------------- Load SlowFast (victim model) ----------------
model = slowfast_r50(pretrained=True).to(device).eval()

# เอา feature ก่อน head
feature_model = torch.nn.Sequential(
    model.blocks[0],
    model.blocks[1],
    model.blocks[2],
    model.blocks[3],
    model.blocks[4],
).to(device).eval()

# ---------------- Feature Temporal Variance ----------------
@torch.no_grad()
def slowfast_ftv(video_cthw, clip_len=8, stride=2):
    C, T, H, W = video_cthw.shape
    prev_feat = None
    sum_sq = 0.0
    count = 0

    for t in range(0, T - clip_len + 1, stride):
        clip = video_cthw[:, t:t+clip_len].unsqueeze(0).to(device)
        clip = resize_for_model(clip)

        inputs = make_slowfast_input(clip.squeeze(0))
        feat_list = feature_model(inputs)   # list: [slow_feat, fast_feat]

        # flatten แต่ละ pathway
        feat_slow = torch.flatten(feat_list[0], 1)
        feat_fast = torch.flatten(feat_list[1], 1)

        # รวม feature
        feat = torch.cat([feat_slow, feat_fast], dim=1).cpu()

        if prev_feat is not None:
            diff = feat - prev_feat
            sum_sq += diff.pow(2).mean().item()
            count += 1

        prev_feat = feat

    return sum_sq / max(count, 1)

# ---------------- Run test ----------------
clean_video = load_video_tensor("sample.mp4", max_frames=128)
poison_video = load_video_tensor("tue_8sec_stronger.mp4", max_frames=128)

clean_ftv = slowfast_ftv(clean_video)
poison_ftv = slowfast_ftv(poison_video)

print("\n======== SLOWFAST FTV (VICTIM TEST) ========")
print("FTV Clean :", clean_ftv)
print("FTV Poison:", poison_ftv)
print("FTV Ratio :", poison_ftv / clean_ftv if clean_ftv > 0 else float("inf"))

# ============================================================
# TEMPORAL FEATURE STABILITY CURVE (LOW-RAM, COLAB-SAFE)
# ||f_t - f_{t-1}||_2 vs time
# ============================================================

!pip install -q opencv-python torch torchvision numpy matplotlib

import cv2
import torch
import numpy as np
import torch.nn.functional as F
import matplotlib.pyplot as plt
from torchvision.models.video import r3d_18, R3D_18_Weights

# ---------------- Device ----------------
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

# ---------------- Utils ----------------
def resize_for_model(video, size=112):
    # video: (1,C,T,H,W)
    n, c, t, h, w = video.shape
    video2 = video.permute(0,2,1,3,4).reshape(n*t, c, h, w)
    video2 = F.interpolate(video2, size=(size, size),
                           mode="bilinear", align_corners=False)
    video2 = video2.reshape(n, t, c, size, size).permute(0,2,1,3,4)
    return video2

def load_video_tensor(path, max_frames=128):
    cap = cv2.VideoCapture(path)
    frames = []
    while len(frames) < max_frames:
        ret, frame = cap.read()
        if not ret:
            break
        frames.append(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
    cap.release()
    video = np.stack(frames).astype(np.float32) / 255.0
    return torch.from_numpy(video).permute(3,0,1,2)  # (C,T,H,W)

# ---------------- Model ----------------
model = r3d_18(weights=R3D_18_Weights.DEFAULT).to(device).eval()
feature_model = torch.nn.Sequential(
    *list(model.children())[:-1]
).to(device).eval()

# ============================================================
# Temporal Feature Stability Curve (streaming)
# ============================================================
@torch.no_grad()
def temporal_feature_diff_curve(video_cthw,
                                 clip_len=8,
                                 stride=2):
    """
    Returns: list of ||f_t - f_{t-1}||_2
    """
    C, T, H, W = video_cthw.shape
    diffs = []
    prev_feat = None

    for t in range(0, T - clip_len + 1, stride):
        clip = video_cthw[:, t:t+clip_len].unsqueeze(0).to(device)
        clip_small = resize_for_model(clip)
        feat = feature_model(clip_small).flatten(1).cpu()

        if prev_feat is not None:
            d = torch.norm(feat - prev_feat, p=2).item()
            diffs.append(d)

        prev_feat = feat

        del clip, clip_small, feat
        if device == "cuda":
            torch.cuda.empty_cache()

    return diffs

# ============================================================
# LOAD VIDEOS
# ============================================================
clean_video  = load_video_tensor("sample.mp4", max_frames=128)
poison_video = load_video_tensor("tue_8sec_stronger.mp4", max_frames=128)

# ============================================================
# COMPUTE CURVES
# ============================================================
clean_curve = temporal_feature_diff_curve(
    clean_video, clip_len=8, stride=2
)

poison_curve = temporal_feature_diff_curve(
    poison_video, clip_len=8, stride=2
)

# ============================================================
# PLOT
# ============================================================
plt.figure(figsize=(10,4))
plt.plot(clean_curve, label="Clean", linewidth=2)
plt.plot(poison_curve, label="Poisoned", linewidth=2)
plt.xlabel("Time step")
plt.ylabel(r"$\|f_t - f_{t-1}\|_2$")
plt.title("Temporal Feature Stability Curve")
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

# ---------------- Quick numeric summary ----------------
print("\n===== Curve Statistics =====")
print("Clean  | mean:", np.mean(clean_curve), " std:", np.std(clean_curve))
print("Poison | mean:", np.mean(poison_curve), " std:", np.std(poison_curve))
print("Mean Ratio:", np.mean(poison_curve) / np.mean(clean_curve))

# ============================================================
# TUEs – WINDOW-BASED (STRONGER FTV, NO OOM, NO BLACK) ✅ NEW
# Google Colab – COPY & RUN
# - window-based ลด OOM
# - save คงขนาดเดิม (ไม่ resize ตอน save)
# - NEW LOSS: maximize Feature Temporal Variance (FTV) จริงๆ
# - มี metric: Pixel TV + Feature TV (Pre-encode / Post-encode)
# ============================================================

!pip install -q opencv-python torch torchvision numpy tqdm ffmpeg-python

import os, cv2, torch
import numpy as np
import torch.nn.functional as F
from torchvision.models.video import r3d_18, R3D_18_Weights
from tqdm import tqdm
from google.colab import files
import time

# ---------------- Device ----------------
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

# ---------------- Download video ----------------
!wget -q -O sample.mp4 https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4

# ---------------- Utils: load frames ----------------
def load_frames(video_path, max_frames=192):
    cap = cv2.VideoCapture(video_path)
    fps = cap.get(cv2.CAP_PROP_FPS)
    if fps is None or fps == 0:
        fps = 30.0

    frames = []
    while len(frames) < max_frames:
        ret, frame = cap.read()
        if not ret:
            break
        frames.append(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
    cap.release()

    print("Loaded frames:", len(frames), "FPS:", fps)
    return frames, fps

# ---------------- Resize (spatial only) for model ----------------
def resize_for_model(video, size=112):
    # video: (N,C,T,H,W)
    n, c, t, h, w = video.shape
    video2 = video.permute(0,2,1,3,4).reshape(n*t, c, h, w)
    video2 = F.interpolate(video2, size=(size, size), mode="bilinear", align_corners=False)
    video2 = video2.reshape(n, t, c, size, size).permute(0,2,1,3,4)
    return video2

# ---------------- Temporal variance (pixel) ----------------
def temporal_variance_cthw(video_cthw):
    # video_cthw: (C,T,H,W) in [0,1]
    diffs = video_cthw[:, 1:] - video_cthw[:, :-1]
    return diffs.pow(2).mean().item()

# ---------------- Flicker term on OUTPUT (stronger than delta-only) ----------------
def output_temporal_inconsistency(poisoned):
    # poisoned: (N,C,T,H,W)
    diffs = poisoned[:, :, 1:] - poisoned[:, :, :-1]
    return torch.mean(diffs**2)

# ---------------- Model (FP32 stable) ----------------
model = r3d_18(weights=R3D_18_Weights.DEFAULT).to(device).eval()
feature_model = torch.nn.Sequential(*list(model.children())[:-1]).to(device).eval()

# ============================================================
# Feature Temporal Variance (FTV) loss inside a window
# - take multiple sub-clips across time
# - maximize feature changes across time
# ============================================================
def ftv_loss_from_window(poisoned_small, clip_len=8, stride=4):
    """
    poisoned_small: (1,3,T,112,112)
    Return: scalar loss that is HIGH when feature changes across time are high
    """
    T = poisoned_small.shape[2]
    feats = []
    for t in range(0, T - clip_len + 1, stride):
        sub = poisoned_small[:, :, t:t+clip_len]            # (1,3,clip_len,112,112)
        feat = feature_model(sub).flatten(1)                # (1,dim)
        feats.append(feat)

    if len(feats) < 2:
        return torch.tensor(0.0, device=poisoned_small.device)

    feats = torch.cat(feats, dim=0)                         # (K,dim)
    diffs = feats[1:] - feats[:-1]
    return torch.mean(diffs**2)                             # high = more temporal disruption

# ============================================================
# TUEs poisoning for ONE WINDOW ✅ STRONGER LOSS
# - maximize FTV (feature temporal disruption)
# - add pixel flicker on output
# - keep perturbation bounded
# ============================================================
def poison_window(frames,
                 steps=30,
                 eps=4/255,
                 lr=2e-3,
                 w_ftv=1.5,
                 w_pix=0.3,
                 clip_len=8,
                 clip_stride=4):
    """
    frames: list RGB uint8 length T
    returns: poisoned_chunk_uint8, metrics dict (pre-encode)
    """
    video = np.stack(frames).astype(np.float32) / 255.0                 # (T,H,W,3)
    video = torch.from_numpy(video).permute(3,0,1,2).unsqueeze(0).to(device)  # (1,3,T,H,W)

    delta = torch.zeros_like(video, requires_grad=True)
    opt = torch.optim.Adam([delta], lr=lr)

    for _ in range(steps):
        opt.zero_grad()

        poisoned = torch.clamp(video + delta, 0, 1)

        # model view (112) only for feature loss
        poisoned_small = resize_for_model(poisoned)

        # NEW: maximize feature temporal variance (FTV)
        ftv = ftv_loss_from_window(poisoned_small, clip_len=clip_len, stride=clip_stride)

        # also encourage visible flicker in pixel domain (but keep small weight)
        pix_flicker = output_temporal_inconsistency(poisoned)

        # minimize negative => maximize both
        loss = -(w_ftv * ftv + w_pix * pix_flicker)

        loss.backward()
        opt.step()

        with torch.no_grad():
            delta.clamp_(-eps, eps)

    with torch.no_grad():
        out = torch.clamp(video + delta, 0, 1)

    # ---- metrics BEFORE encode ----
    clean_tv = temporal_variance_cthw(video.squeeze(0).detach().cpu())
    pois_tv  = temporal_variance_cthw(out.squeeze(0).detach().cpu())
    ratio_tv = (pois_tv / clean_tv) if clean_tv > 0 else float("inf")

    diff = (out - video).detach()
    l_inf = diff.abs().max().item()
    l2 = (torch.norm(diff).item() / diff.numel())

    # convert to uint8 frames (keep original H,W)
    out_np = out.squeeze(0).permute(1,2,3,0).cpu().numpy()
    out_np = np.clip(out_np, 0, 1)
    out_u8 = (out_np * 255).astype(np.uint8)

    metrics = {
        "pixel_tv_clean": clean_tv,
        "pixel_tv_pois": pois_tv,
        "pixel_tv_ratio": ratio_tv,
        "l_inf": l_inf,
        "l2_norm_per_elem": l2
    }
    return out_u8, metrics

# ============================================================
# SAFE Feature Temporal Variance metric (no RAM crash)
# ============================================================
@torch.no_grad()
def load_video_tensor(path, max_frames=128):
    cap = cv2.VideoCapture(path)
    frames = []
    while len(frames) < max_frames:
        ret, frame = cap.read()
        if not ret:
            break
        frames.append(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
    cap.release()
    video = np.stack(frames).astype(np.float32) / 255.0
    return torch.from_numpy(video).permute(3,0,1,2)  # (C,T,H,W)

@torch.no_grad()
def feature_temporal_variance_stream(video_cthw, clip_len=8, stride=2):
    C, T, H, W = video_cthw.shape
    prev_feat = None
    sum_sq = 0.0
    count = 0

    for t in range(0, T - clip_len + 1, stride):
        clip = video_cthw[:, t:t+clip_len].unsqueeze(0).to(device)  # (1,C,T,H,W)
        clip_small = resize_for_model(clip)
        feat = feature_model(clip_small).flatten(1).cpu()

        if prev_feat is not None:
            diff = feat - prev_feat
            sum_sq += diff.pow(2).mean().item()
            count += 1

        prev_feat = feat

        del clip, clip_small, feat
        if device == "cuda":
            torch.cuda.empty_cache()

    return sum_sq / max(count, 1)

# ---------------- Run (WINDOWED) ----------------
all_results = []

eps_list = [1/255, 2/255, 3/255, 4/255, 5/255, 6/255, 7/255, 8/255]

frames, fps = load_frames("sample.mp4", max_frames=192)

for eps in eps_list:
    print(f"\n================ EPS = {eps:.6f} =================")

    # reset frames
    if os.path.exists("frames"):
        for f in os.listdir("frames"):
            os.remove(os.path.join("frames", f))
    else:
        os.makedirs("frames", exist_ok=True)

    window = 24
    idx = 0
    pre_metrics = []

    poison_start_time = time.time()

    for i in tqdm(range(0, len(frames), window)):
        chunk = frames[i:i+window]
        if len(chunk) < 2:
            break

        poisoned_chunk_u8, m = poison_window(
            chunk,
            steps=30,
            eps=eps,              # <<< sweep eps ตรงนี้
            lr=2e-3,
            w_ftv=1.5,
            w_pix=0.3,
            clip_len=8,
            clip_stride=4
        )
        pre_metrics.append(m)

        for f in poisoned_chunk_u8:
            cv2.imwrite(f"frames/{idx:05d}.png",
                        cv2.cvtColor(f, cv2.COLOR_RGB2BGR))
            idx += 1

        if device == "cuda":
            torch.cuda.empty_cache()

    poison_time = time.time() - poison_start_time

    # ---------- encode ----------
    out_name = f"tue_eps_{int(eps*255)}.mp4"
    !ffmpeg -y -framerate {fps} \
      -i frames/%05d.png \
      -c:v libx264 -preset slow -crf 14 -tune grain \
      -pix_fmt yuv420p {out_name}

    # ---------- aggregate metrics ----------
    avg_clean_tv = np.mean([m["pixel_tv_clean"] for m in pre_metrics])
    avg_pois_tv  = np.mean([m["pixel_tv_pois"]  for m in pre_metrics])
    avg_ratio_tv = np.mean([m["pixel_tv_ratio"] for m in pre_metrics])
    avg_linf     = np.mean([m["l_inf"] for m in pre_metrics])

    # feature TV (safe)
    orig_ftv = feature_temporal_variance_stream(
        load_video_tensor("sample.mp4", 128)
    )
    pois_ftv = feature_temporal_variance_stream(
        load_video_tensor(out_name, 128)
    )

    ftv_ratio = pois_ftv / orig_ftv if orig_ftv > 0 else float("inf")
    efficiency = ftv_ratio / avg_linf

    result = {
        "eps": eps,
        "pixel_tv_ratio": avg_ratio_tv,
        "ftv_ratio": ftv_ratio,
        "l_inf": avg_linf,
        "efficiency": efficiency,
        "time_sec": poison_time,
        "output": out_name
    }

    all_results.append(result)

    print("Result:", result)

# ---------------- Encode (preserve temporal noise more) ----------------
# NOTE: use tune=grain + lower crf to keep flicker detail
# !ffmpeg -y -framerate {fps} \
#   -i frames/%05d.png \
#   -c:v libx264 -preset slow -crf 14 -tune grain \
#   -pix_fmt yuv420p tue_8sec_stronger.mp4

# ---------------- Quick visual check (non-black) ----------------
import matplotlib.pyplot as plt

def read_frame_at(path, frame_idx=30):
    cap = cv2.VideoCapture(path)
    cap.set(cv2.CAP_PROP_POS_FRAMES, frame_idx)
    ret, frame = cap.read()
    cap.release()
    if not ret:
        raise ValueError(f"Cannot read frame {frame_idx} from {path}")
    return cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

f1 = read_frame_at("sample.mp4", 30)
f2 = read_frame_at(all_results[-1]["output"], 30)

plt.figure(figsize=(10,4))
plt.subplot(1,2,1); plt.title("Original"); plt.imshow(f1); plt.axis("off")
plt.subplot(1,2,2); plt.title("Poisoned (Stronger)"); plt.imshow(f2); plt.axis("off")
plt.show()

# ---------------- Aggregate PRE-ENCODE pixel metrics ----------------
avg_clean_tv = np.mean([m["pixel_tv_clean"] for m in pre_metrics])
avg_pois_tv  = np.mean([m["pixel_tv_pois"]  for m in pre_metrics])
avg_ratio_tv = np.mean([m["pixel_tv_ratio"] for m in pre_metrics])
avg_linf     = np.mean([m["l_inf"] for m in pre_metrics])

print("\n======== PRE-ENCODE (WINDOW AVG) ========")
print("Pixel Temporal Variance (Clean):", avg_clean_tv)
print("Pixel Temporal Variance (Poison):", avg_pois_tv)
print("Pixel Variance Ratio:", avg_ratio_tv)
print("L_inf (max perturbation):", avg_linf)

# ---------------- Post-encode Pixel TV ----------------
# orig_t = load_video_tensor("sample.mp4", max_frames=192)
# pois_t = load_video_tensor("tue_8sec_stronger.mp4", max_frames=192)

# tv_orig_post = temporal_variance_cthw(orig_t)
# tv_pois_post = temporal_variance_cthw(pois_t)

# print("\n======== POST-ENCODE PIXEL METRICS (AFTER H.264) ========")
# print("Pixel Temporal Variance (Clean):", tv_orig_post)
# print("Pixel Temporal Variance (Poison):", tv_pois_post)
# print("Pixel Variance Increase Ratio:", (tv_pois_post / tv_orig_post) if tv_orig_post > 0 else float("inf"))

# ---------------- Feature Temporal Variance (FTV) PRE/POST ----------------
# (วัดจากไฟล์ mp4 แบบ safe)
# orig_ftv = feature_temporal_variance_stream(load_video_tensor("sample.mp4", 128), clip_len=8, stride=2)
# pois_ftv = feature_temporal_variance_stream(load_video_tensor("tue_8sec_stronger.mp4", 128), clip_len=8, stride=2)

# print("\n======== FEATURE TEMPORAL VARIANCE (SAFE) ========")
# print("Feature Temporal Variance (Clean): ", orig_ftv)
# print("Feature Temporal Variance (Poison):", pois_ftv)
# print("FTV Ratio:", (pois_ftv / orig_ftv) if orig_ftv > 0 else float("inf"))

# print(f"Total poisoning time (exclude load/encode): {poison_total_time:.2f} seconds")

# files.download("tue_8sec_stronger.mp4")

import pandas as pd

df = pd.DataFrame(all_results)
df = df.sort_values("efficiency", ascending=False)
df

# ============================================================
# TUEs – WINDOW-BASED @ 40/255 (FORCED PIXEL STRENGTH)
# COPY & RUN (Google Colab)
# - target l_inf ≈ 40/255
# - strong pixel + strong FTV
# ============================================================

!pip install -q opencv-python torch torchvision numpy tqdm ffmpeg-python

import os, cv2, torch, time
import numpy as np
import torch.nn.functional as F
from torchvision.models.video import r3d_18, R3D_18_Weights
from tqdm import tqdm

# ---------------- Device ----------------
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

# ---------------- Download sample video ----------------
!wget -q -O sample.mp4 https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4

# ---------------- Config (IMPORTANT) ----------------
TARGET_EPS = 10 / 255        # <<< เป้าหมาย perturbation
STEPS = 80                  # เพิ่ม step ให้ delta ชน eps
LR = 1e-2                   # learning rate ของ delta
W_FTV = 1.5                 # feature temporal variance
W_PIX = 2.5                 # <<< ดัน pixel ให้ขยับจริง
WINDOW = 24                 # ~1 sec
# ----------------------------------------------------

# ---------------- Utils ----------------
def load_frames(video_path, max_frames=192):
    cap = cv2.VideoCapture(video_path)
    fps = cap.get(cv2.CAP_PROP_FPS) or 30.0
    frames = []
    while len(frames) < max_frames:
        ret, frame = cap.read()
        if not ret:
            break
        frames.append(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
    cap.release()
    print("Loaded frames:", len(frames), "FPS:", fps)
    return frames, fps


def resize_for_model(video, size=112):
    n, c, t, h, w = video.shape
    x = video.permute(0,2,1,3,4).reshape(n*t, c, h, w)
    x = F.interpolate(x, size=(size, size), mode="bilinear", align_corners=False)
    x = x.reshape(n, t, c, size, size).permute(0,2,1,3,4)
    return x


def output_temporal_inconsistency(video):
    return ((video[:, :, 1:] - video[:, :, :-1]) ** 2).mean()


# ---------------- Model ----------------
model = r3d_18(weights=R3D_18_Weights.DEFAULT).to(device).eval()
feature_model = torch.nn.Sequential(*list(model.children())[:-1]).to(device).eval()


def ftv_loss_from_window(video_small, clip_len=8, stride=4):
    T = video_small.shape[2]
    feats = []
    for t in range(0, T - clip_len + 1, stride):
        clip = video_small[:, :, t:t+clip_len]
        feat = feature_model(clip).flatten(1)
        feats.append(feat)
    if len(feats) < 2:
        return torch.tensor(0.0, device=device)
    feats = torch.cat(feats, 0)
    return ((feats[1:] - feats[:-1]) ** 2).mean()


# ---------------- Poison ONE window ----------------
def poison_window(frames):
    video = np.stack(frames).astype(np.float32) / 255.0
    video = torch.from_numpy(video).permute(3,0,1,2).unsqueeze(0).to(device)

    delta = torch.zeros_like(video, requires_grad=True)
    opt = torch.optim.Adam([delta], lr=LR)

    for step in range(STEPS):
        opt.zero_grad()

        poisoned = torch.clamp(video + delta, 0, 1)
        poisoned_small = resize_for_model(poisoned)

        ftv = ftv_loss_from_window(poisoned_small)
        pix = output_temporal_inconsistency(poisoned)

        loss = -(W_FTV * ftv + W_PIX * pix)
        loss.backward()
        opt.step()

        with torch.no_grad():
            delta.clamp_(-TARGET_EPS, TARGET_EPS)

        if step % 10 == 0:
            linf_now = delta.abs().max().item() * 255
            print(f"step {step:02d} | l_inf ≈ {linf_now:.2f}/255")

    with torch.no_grad():
        out = torch.clamp(video + delta, 0, 1)

    diff = (out - video).abs().max().item() * 255
    print(f"FINAL l_inf ≈ {diff:.2f}/255")

    out_np = out.squeeze(0).permute(1,2,3,0).cpu().numpy()
    return (out_np * 255).astype(np.uint8)


# ---------------- RUN ----------------
frames, fps = load_frames("sample.mp4", 192)

os.makedirs("frames", exist_ok=True)
idx = 0

start = time.time()

for i in tqdm(range(0, len(frames), WINDOW)):
    chunk = frames[i:i+WINDOW]
    if len(chunk) < 2:
        break

    poisoned_chunk = poison_window(chunk)

    for f in poisoned_chunk:
        cv2.imwrite(
            f"frames/{idx:05d}.png",
            cv2.cvtColor(f, cv2.COLOR_RGB2BGR)
        )
        idx += 1

    if device == "cuda":
        torch.cuda.empty_cache()

print("Poisoning time:", time.time() - start, "sec")

# ---------------- Encode ----------------
!ffmpeg -y -framerate {fps} \
  -i frames/%05d.png \
  -c:v libx264 -preset slow -crf 14 -tune grain \
  -pix_fmt yuv420p tue_eps_40.mp4

print("DONE -> tue_eps_40.mp4")